### ISSUE TITLE
Split API and Models into separate packages

### ISSUE THREAD

**Issue by ubergesundheit** [sensebox/openSenseMap-API#113]
Todo:

- [x] Document NPM release and Docker image building
- [x] Set up automatic image building from tags on Docker hub (https://stackoverflow.com/a/44796846)
- [x] Publish MQTT client on github and NPM
- [ ] Come up with some sort of connection between api and mqtt, to be used by future services and ttn-integration
  - Should have client libraries for at least Node.Js and Go
  - http://nsq.io/ Delivers per design messages only to one client
  - Maybe gRPC with service mesh
    - Should allow to broadcast to all services (like reload config from db)
    - Should do load balancing of requests (just send mail once and not from every service)
    - Services of the same kind should know which other services handle stuff (like restarted services know where to pick up.)

Timeline:
- [x] Merge #116 from `development` into `master`
- [x] Prepare [sensebox/openSenseMap-API-models](https://github.com/sensebox/openSenseMap-API-models) for proper use
  - [x] sensebox/openSenseMap-API-models#2 & sensebox/openSenseMap-API-models#1
- [x] Merge #115 into `development`
- [x] Update Deployment of services [sensebox/OSeM-compose](https://github.com/sensebox/OSeM-compose)
